version: "2"

run:
  timeout: 5m
  build-tags:
    - afp
    - macgarden
    - macip

linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

linters-settings:
  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - errcheck
