[Logging]
level = 'debug'
parse_packets = true
log_traffic = false

[Router]

[Bridge]
mode = 'pcap'
device = '\Device\NPF_{9354BA7F-DE41-4A33-88F4-408A0F4A3C02}'
hw_address = 'DE:AD:BE:EF:CA:FE'
bridge_mode = 'auto'

[LToUdp]
enabled = true
interface = '0.0.0.0'
seed_network = 1
seed_zone = 'LToUDP Network'

[TashTalk]
port = ''
seed_network = 2
seed_zone = 'TashTalk Network'

[EtherTalk]
seed_network_min = 3
seed_network_max = 5
seed_zone = 'EtherTalk Network'
desired_network = 3
desired_node = 253

[Capture]
localtalk = './captures/afp-localtalk.pcap'
ethertalk = './captures/afp-ethertalk.pcap'
ipx = './captures/ipx.pcap'
netbeui = './captures/netbeui.pcap'
snaplen = 65535

[MacIP]
enabled = true
mode = 'pcap'
nat_subnet = '192.168.100.0/24'
lease_file = 'leases.txt'
dhcp_relay = true
nameserver = '1.1.1.1'

[IPX]
enabled = true
framing = 'ethernet_ii'

[IPXGW]
enabled = true
bindings = ['ClassicStack:EtherTalk Network']

[NetBEUI]
enabled = true

[NetBIOS]
enabled = true
transports = ['ipx', 'netbeui']

[SMB]
enabled = true
nbt_binding = ':139'
server_name = 'ClassicStack'
workgroup = 'WORKGROUP'

[SMB.Volumes]
[SMB.Volumes.Public]
name = 'Public'
path = 'C:\Mac'
fs_type = 'local_fs'

[AFP]
enabled = true
name = 'ClassicStack'
zone = 'EtherTalk Network'
protocols = 'ddp,tcp'
binding = ':548'
extension_map = 'extmap.conf'
cnid_backend = 'sqlite'
use_decomposed_names = true
appledouble_mode = 'modern'

[AFP.Volumes]
[AFP.Volumes.Default]
name = 'Welcome'
path = './dist/Sample Volume'
read_only = true

[AFP.Volumes.MacGarden]
name = 'Mac Garden'
fs_type = 'macgarden'

[AFP.Volumes.TestVolume]
name = 'Test Volume'
path = 'C:\Mac\Test'
appledouble_mode = 'modern'

[AFP.Volumes.Volume68k]
name = 'Volume 68K'
path = 'C:\Mac\Volume68K'
appledouble_mode = 'legacy'

[Shortname]
windows_shortnames = true
backend = 'memory'

[WebUI]
enabled = true
bind = '127.0.0.1:8089'
tls = true
